---

namespaces:
  - namespace: production
    branch: main
  - namespace: staging
    branch: develop
  - namespace: as-branch
    branch: features/*
files:
  - deployment.yml
  - service.yml
directories: []
