---

namespaces:
  - namespace: production
    branch: main
  - namespace: staging
    branch: develop
  - namespace: ns-creation-test
    branch: features/*
manifests:
  - deployment.yml
  - service.yml
